/*
Copyright (c) 2013, Sibt ul Hussain <sibt.ul.hussain at gmail dot com>
All rights reserved.
Released under BSD License
-------------------------
For license terms please see license.lic
*/
#ifndef INCLUDEHEADERS_H_
#define INCLUDEHEADERS_H_
//#include "lbpRoot.h"
//#include "hogFeatures.h"
//#include "lbpFeatures.h"
//#include "lbpFeatures_256.h"
//#include "lbpFeaturesRGB.h"
//#include "cslbpFeatures.h"
//#include "csltpFeatures.h"
//#include "ltpFeatures.h"
//#include "ltpFeaturesRGB.h"
//#include "onlyltpFeaturesX.h"
//#include "onlyltpFeatures.h"
//#include "hogltpFeatures.h"
//#include "hoglbpFeatures.h"
//#include "hogColorFeatures.h"
#define FEATURES
#ifdef FEATURES
#include "lbpFeaturesRGBBlock.h"
#include "ltpFeaturesRGBCell.h"
#include "onlyLTPFeaturesRGBCell.h"
#include "encodedPatchFeatures.h"
#include "encodedMultipleCBPatchFeatures.h"
#include "encodedMultipleCBPatchFeaturesHistogram.h"
//#include "multipleEncodedPatchFeatures.h"
#include "multipleCBQuantizedLQPFeatures.h"
#include "encodeFeatures.h"
#else
#ifdef WINDOW_CLASSIFIER
#include "lbpRoot.h"
#include "hogFeatures.h"
#include "lbpFeatures.h"
#include "lbpFeatures_256.h"
#include "csLBPFeatures.h"
//#include "csltpFeatures.h"
#include "ltpFeatures.h"
#include "ltpFeaturesRGB.h"
#include "lbpFeaturesRGB.h"
#include "hogLbpFeaturesRGB.h"
#include "hogLtpFeaturesRGB.h"
#include "onlyLtpFeaturesRGB.h"
#include "hogOnlyLtpFeaturesRGB.h"
#include "onlyltpFeaturesX.h"
#include "onlyltpFeatures.h"
#include "hogltpFeatures.h"
#include "hoglbpFeatures.h"
#include "hogColorFeatures.h"
#include "projectedFeatures.h"
#include "projectedLTPFeatures.h"
#include "projectedLTPFeaturesRGB.h"
#include "projectedLBPFeatures.h"
#include "projectedLBPFeaturesRGB.h"
#include "histogramFeatures.h"
#include "histogramFeaturesLLRatio.h"
#include "csLBPFeaturesRGB.h"
#include "csLTPFeaturesRGB.h"
#include "multipleWindowFeatures.h"
//#include "textureFeatures.h"
#else
#include "projectedFeatures.h"
#include "projectedLTPFeatures.h"
#include "projectedLTPFeaturesRGB.h"
#include "projectedOnlyLTPFeaturesRGB.h"
#include "projectedLTPFeaturesEdge.h"
#include "projectedLBPFeatures.h"
#include "projectedLBPFeaturesRGB.h"
#include "projectedLBPHistFeatures.h"
#include "projectedLTPHistFeatures.h"
#include "lbpFeaturesRGBBlock.h"
#include "ltpFeaturesRGBCell.h"
#include "onlyLTPFeaturesRGBCell.h"
//#include "multiLevelFeatures.h"
#include "encodedLTPFeatures.h"
#include "encodedRFPatchFeatures.h"
#include "encodedLBPFeatures.h"
#include "encodedLBPPatchFeatures.h"
#include "encodedLTPPatchFeatures.h"
#include "encodedPatchFeatures.h"
#include "encodedMultipleCBPatchFeatures.h"
#include "encodedMultipleCBPatchFeaturesHistogram.h"
#include "multipleEncodedPatchFeatures.h"
#include "multipleCBQuantizedLQPFeatures.h"
#include "encodeFeatures.h"
#include "LBPPlusPatchFeatures.h"
#include "histogramFeatures.h"
#include "patchPlusOtherFeatures.h"
#include "combinedMultipleFeatures.h"
#include "CSltpFeaturesRGBCell.h"
#endif
#endif /* INCLUDEHEADERS_H_ */
#endif
